[package]
name = "gcn_agg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ramulator-wrapper={path="../ramulator-wrapper"}
itertools="*"
lazy_static="*"